### ISSUE TITLE
Report summary crashes on Windows 10

### ISSUE THREAD

**Issue by mhwaage** [tophat/syrupy#633]
**Describe the bug**
When printing a summary of snapshots, syrupy formats the text using `colored.fg`. This triggers a crash, as `colored.fg` uses incorrect types when interfacing with the kernel32 dll.

An [issue](https://gitlab.com/dslackw/colored/-/issues/25) and corresponding [merge request](https://gitlab.com/dslackw/colored/-/merge_requests/19) has been created on colored's repository.

Unfortunately, this can not be bypassed via `--snapshot-no-colors` or other environment variables, as the call to `colored.fg` occurs _before_ we check for those.

**To reproduce**
Run any snapshot test on (the above version of) Windows.
Result:
```
-------------- snapshot report summary --------------- 
Traceback (most recent call last):
  File "...\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "...\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "...\lib\site-packages\_pytest\config\__init__.py", line 162, in main       
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "...\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "...\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "...\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "...\lib\site-packages\_pytest\main.py", line 316, in pytest_cmdline_main   
    return wrap_session(config, _main)
  File "...\lib\site-packages\_pytest\main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "...\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "...\lib\site-packages\_pytest\terminal.py", line 813, in pytest_sessionfinish
    self.config.hook.pytest_terminal_summary(
  File "...\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "...\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "...\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "...\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "...\lib\site-packages\syrupy\__init__.py", line 170, in pytest_terminal_summary
    for line in terminalreporter.config._syrupy.report.lines:
  File "...\lib\site-packages\syrupy\report.py", line 277, in lines
    ).format(green(self.num_updated))
  File "...\lib\site-packages\syrupy\terminal.py", line 34, in green
    return _stylize(text, colored.fg("green"))
  File "...\lib\site-packages\colored\colored.py", line 431, in fg
    return colored(color).foreground()
  File "...\lib\site-packages\colored\colored.py", line 23, in __init__
    self.enable_windows_terminal_mode()
  File "...\lib\site-packages\colored\colored.py", line 374, in enable_windows_terminal_mode
    hStdout = windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: 
wrong type
```

**Expected behavior**
No crash

**Environment (please complete the following information):**
- OS: Windows 10 Enterprise 21H2 19044.2130
- Syrupy Version: 3.0.4
- Python Version: Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
- (Colored Version: 1.4.3)

**Additional context**
It would be helpful if specifying `NO_COLOR` et al. would pre-empt calling `colored.fg` - that way, we would be able to bypass the issue without any nasty hacks. In lieu of that, the following nasty hack acts as a workaround:

In the test module (or possibly conftest.py, haven't checked), add:
```
import colored

colored.colored.enable_windows_terminal_mode = lambda self: None
```
Then run the tests as normal ( possibly with `--snapshot-no-colors`, although I didn't notice any difference).

**Comment by mhwaage** [comment]
It is a bit strange that this is making it through the integration tests, so I expect this to be a problem only on some Windows configurations.

**Comment by noahnu** [comment]
Are you interested in contributing your proposed fix? (i.e. not call colored.fg if NO_COLOR is set)

> It is a bit strange that this is making it through the integration tests, so I expect this to be a problem only on some Windows configurations.

Are you able to run syrupy tests on this windows machine? It'd be helpful to try debug why our windows github workflow doesn't catch this

**Comment by mhwaage** [comment]
I'll have a look at the tests and see if I can make an example that actually fails them (they also pass on my machine, so might be more convoluted still!) If I can get it working, I can also have a look at implementing the proposed change, sure!

**Comment by mhwaage** [comment]
Did still more testing and found that the issue has a weird form of semi-determinism; in my closest attempt at reproducing the issue in a 'clean' environment (looking only at colored, but with other libraries installed), I managed to trigger it from terminal, but not when running the exact same commands in a script.

The merge request I mentioned was accepted, so should be fixed in the next colored release, anyway, but I will still make a draft PR for only calling colored when NO_COLOR hasn't been set.
